{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-jmx-exporter.fullname" . }}
  labels:
    {{- include "prometheus-jmx-exporter.labels" . | nindent 4 }}
    release: prometheus-operator
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  {{- range $k, $v := .Values.serviceMonitor.endpoints }}
  {{- range $q,$c := $v.query }}
  - interval: {{ default "1m" $v.interval }}
    scrapeTimeout: {{ default "40s" $v.scrapeTimeout }}
    path: /metrics
    port: metrics
    params:
      target:
      - {{ $v.name }}
      timeout:
      - {{ default "35" $v.timeout | quote }}
      query:
      - {{ $c.name | quote }}
      {{- if $c.labels }}
      labels:
      - {{ $c.labels | quote }}
      {{- end }}
  {{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "prometheus-jmx-exporter.labels" . | nindent 6 }}
  {{- end }}